services:
  minio:
    image: minio/minio:RELEASE.2024-08-03T04-33-23Z
    container_name: minio
    ports:
      - 9000:9000
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=******
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    networks:
      - backend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.minio.rule=Host(`data.${PRIMARY_DOMAIN}`)"
      - "traefik.http.routers.minio.entrypoints=websecure"
      - "traefik.http.routers.minio.tls.certresolver=letsencrypt"
      - "traefik.http.services.minio.loadbalancer.server.port=9001"
    healthcheck:
      test: [ "CMD", "curl", "-k", "http://localhost:9000/minio/health/live" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s

volumes:
  minio_data:
    external: true

networks:
  backend:
    external: true
